steps:
  # Install
  - name: "node:10.15.1"
    entrypoint: yarn
    args: ["install"]

  # Test
  - name: "node:10.15.1"
    entrypoint: yarn
    args: ["run", "test:ci"]

  # Build
  - name: "node:10.15.1"
    entrypoint: yarn
    args: ["run", "build"]

  # Deploy
  - name: "node:10.15.1"
    entrypoint: yarn
    args: ["run", "deploy"]
