steps:
  # Install
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]

  # Test
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "test"]

  # Build
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "build"]
