steps:
  # Install
  - name: 'node:16.13.1'
    entrypoint: npm
    args: ['install']

  # Test
  - name: 'node:16.13.1'
    entrypoint: npm
    args: ['run', 'test:ci']

  # Build
  - name: 'node:16.13.1'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy
  # - name: 'gcr.io/$PROJECT_ID/firebase'
  #   args: ['deploy']
