steps:
  # Install
  - name: "gcr.io/cloud-builders/npm:node-10.13.0"
    args: ["install"]

  # Test
  - name: "gcr.io/cloud-builders/npm:node-10.13.0"
    args: ["run", "test"]

  # Build
  - name: "gcr.io/cloud-builders/npm:node-10.13.0"
    args: ["run", "build"]
