export { default as Home } from './Home/Home'
export { default as Navigation } from '../common/Navigation/Navigation'
export { default as Resume } from './Resume/Resume'
export { default as Blog } from './Blog/Blog'
export { NewHome } from './NewHome/Home.jsx'
